name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - names: Print greeting
        run: echo "Hello World!"
      - names: Print goodbye
        run: echo "Done goodbye!"
